cart/urls.py
from django.urls import path

from .views import cart_add, cart_detail, cart_remove

urlpatterns = [
    path('', cart_detail, name='cart_detail'),
    path('add/<int:pk>/', cart_add, name='cart_add'),
    path('remove/<int:pk>/', cart_remove, name='cart_remove'),
]

django_project/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import include, path

urlpatterns = i18n_patterns(
    path("admin/", admin.site.urls),
    path("administrating/", include("products.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("cart/", include("cart.urls")),
    path("order/", include("orders.urls")),
    path("", include("pages.urls")),
)

products/models.py
import boto3
from boto3.session import Session
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from imagekit.models import ProcessedImageField
from PIL import Image

# from raw_sugar import RawManager

# Create your models here.
# def get_currencies():
#     return {i: i for i in settings.CURRENCIES}

def generate_path_and_image(instance, filename):
    return 'item_pictures/' + str(instance.item_id) + '.' + 'webp'


class Item(models.Model):
    class AdditionalInfo(models.TextChoices):
        FancyProduct = 'Fancy Product', _('Fancy Product') #Новинка
        Sale = 'Sale', _('Sale')                           #Распродажа
        SpecialItem = 'Special Item', _('Special Item')    #Спец предложение
        Bestseller = 'Bestseller', _('Bestseller')         #Хит продаж
        __empty__ = _("Unknown")
        InStock = 'In Stock',_('In Stock')                 #В наличии
        NotInStock = 'Not In Stock',_('Not In Stock')      #Не в наличии
        
    item_id = models.IntegerField(auto_created=True, unique=True, verbose_name=_('item number'))
    item_author_id = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        auto_created=True,
        on_delete=models.CASCADE,
        verbose_name=_('author')
        )

    # Валидация будет во view. Если ни одно из наименований не будет заполнено, сохранено не будет
    # Валидацию также нужно будет по соответствию яык наименования (ячейка) = языку текста (ячейка) = выбранная валюта
    # При выборе языка будут отражаться только те товары, которые были добавлены на данном языке
    # Соответственно валюта будет автоматически отражаться в зависимости от языка
    # китайский - юань, русский - рубль
    # вопрос к евро и доллару - зависит от направленности торговли, для Европы - евро, Штаты - доллар
    # Если добавить возможность выбора валюты на сайте, тогда это будет только в ознакомительных целях
    # При добавлении в корзину цена будет указана в двух валютах - валюте рассчета, в зависимости от выбранного языка
    # и в "ознакомительной валюте"
    # Что если пользователь выберет один язык, добавит в корзину товар, затем переключит язык 
    # и попытается добавить товар? Разные цены и разные регионы.
    # Нужно будет реализовать невозможность поменять язык или невозможность добавить товар в корзину с другой валютой
    # По окончанию оформления товара вывести сообщение: Ваш заказ получен, в ближайшее время с вами свяжется
    # оператор для уточнения деталей заказа.
    item_name_en = models.CharField(max_length=200, unique=True, blank=True, null=True, verbose_name=_('item name in English'), db_index=True)
    item_name_ru = models.CharField(max_length=200, unique=True, blank=True, null=True, verbose_name=_('item name in Russian'), db_index=True)
    item_name_zh_hans = models.CharField(max_length=200,unique=True, blank=True, null=True, verbose_name=_('item name in Chinese'), db_index=True)
    
    item_category_number = models.ForeignKey(
        'Category',
        on_delete=models.CASCADE,
        verbose_name=_('category')
    )
    # в файле отработчике написать логику конвертирования в формат webp
    # добавить в отработчик переименование файла в соответствие с item_name
    item_picture = ProcessedImageField(verbose_name=_('picture'), upload_to=generate_path_and_image,
                             format='WEBP',
                             options={'quality': 70}) # upload_to="item_pictures"
    
    item_description_en = models.TextField(blank=True, verbose_name=_('item description in English'), db_index=True)
    item_description_ru = models.TextField(blank=True, verbose_name=_('item description in Russian'), db_index=True)
    item_description_zh_hans = models.TextField(blank=True, verbose_name=_('item description in Chinese'), db_index=True)
    
    item_extra_tag = models.CharField(choices=AdditionalInfo, default=AdditionalInfo.__empty__, verbose_name=_('item extra tag'))
    
    item_price = models.DecimalField(max_digits=5, decimal_places=2, verbose_name=_('item price'), db_index=True)
    item_price_extra_new = models.DecimalField(max_digits=5, decimal_places=2, blank=True, null=True, verbose_name=_('extra new item price'), db_index=True)
    item_price_currency = models.CharField(max_length=3, choices=settings.CURRENCY_CHOICES, default='RUB', verbose_name=_('item price currency'))
    
    item_published_at = models.DateField(auto_now_add=True, db_index=True)
    
    # objects = RawManager()
    
    # slug = models.SlugField('Название в виде url', max_length=200)
    
    # def get_absolute_url(self):
    #     return reverse('post_detail', args={'slug': self.slug})
    
    class Meta:
        verbose_name = _("item")
        verbose_name_plural = _("items")
        ordering = ["-item_published_at"]
        
        
    def __str__(self) -> str:
        return str(self.item_id)
        # if self.item_name_en == '':
        #     if self.item_name_ru == '':
        #         if self.item_name_zh_Hans == '':
        #             return ValueError
        #         else:
        #             return self.item_name_zh_Hans
        #     else:
        #         return self.item_name_ru
        # else:
        #     return self.item_name_en
        
        
        # for i in [self.item_name_en, self.item_name_ru, self.item_name_zh_Hans]:
        #     if i != '':
        #         return i

    def get_absolute_url(self):
        # return reverse("item_all")
        return reverse('item_detail', kwargs={'pk': self.pk}) #args=[str(self.pk)])
    
    def delete(self, *args, **kwargs):
        session = Session(settings.AWS_ACCESS_KEY_ID, settings.AWS_SECRET_ACCESS_KEY)
        s3_resource = session.resource('s3')
        s3_bucket = s3_resource.Bucket(settings.AWS_STORAGE_BUCKET_NAME)
        
        file_path = 'media/' + str(self.item_picture)
        response = s3_bucket.delete_objects(
            Delete={
                'Objects': [
                    {
                        'Key': file_path
                    }
                ]
            })
        # return super(Item, self).delete(*args, **kwargs)
        
        # s3 = boto3.resource('s3')
        # session = Session (settings.AWS_ACCESS_KEY_ID, settings.AWS_SECRET_ACCESS_KEY)
        # object = s3_resource.Object(settings.AWS_STORAGE_BUCKET_NAME, str(self.item_picture)).delete()
                
        return super(Item, self).delete(*args, **kwargs)


class Category(models.Model):
    category_number = models.IntegerField(auto_created=True, unique=True, verbose_name=_('category number'), db_index=True)
    author_id = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        auto_created=True,
        on_delete=models.CASCADE,
        verbose_name=_('author')
        )

    category_name_ru = models.CharField(max_length=50, verbose_name=_('category name in Russian'), db_index=True)
    category_name_en = models.CharField(max_length=50, verbose_name=_('category name in English'), db_index=True)
    category_name_zh_hans = models.CharField(max_length=50, verbose_name=_('category name in Chinese'), db_index=True)

    
    class Meta:
        verbose_name = _("category")
        verbose_name_plural = _("categories")
        ordering = ["category_number"]
        
        
    def __str__(self) -> str:
        # return str(self.category_number)
        return self.category_name_ru
        
    
    def right_language(self):
        language = 'information'
        return language
    
    
    def get_absolute_url(self):
        return reverse("category_all")
    

templates/cart_detail.html
{% extends "_base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Cart" %}{% endblock title %}

{% block content %}
<div class="container mt-3">    
    <h1 class="h1 border-bottom pb-3 border-light border-opacity-25">{% trans "Your shopping cart" %} </h1>
    {% if cart %}
    <div class='card' style="border-color: #8B4513;">
        <div class='card-header'>
            <span class='font-weight-bold'> Your name / Guest </span> &middot;
            <span class='text-muted'>
                Date
            </span>
        </div>
        <div class='card-body'>
              <table style="width:100%;">
                <tr>
                  <th style="text-align: center; width: 20%;">{% trans "Image" %}</th> 
                  <th style="text-align: center; width: 40%;">{% trans "Item" %}</th>
                  <th style="text-align: center; width: 10%;">{% trans "Quantity" %}</th>
                  <th style="text-align: center; width: 10%;">{% trans "Remove" %}</th>
                  <th style="text-align: center; width: 10%;">{% trans "Unit price" %}</th>
                  <th style="text-align: center; width: 10%;">{% trans "Price" %}</th>
                </tr>
                {% comment %} {{ in_cart }} {% endcomment %}

                {% for item in cart %}
                
                <tr>
                  <td style="text-align: center;"><img src="{{ item.item.item_picture.url }}" style="max-width: 70px;"></td>
                  <td style="text-align: center;">{{ item.name }}</td> 
                  <td style="text-align: center;">{{ item.quantity }}</td>
                  <td style="text-align: center;"><a href="#">{% trans "Remove" %}</a></td>
                  {% comment %} <td style="text-align: center;"><a href="{% url 'cart_remove' item.id %}">{% trans "Remove" %}</a></td> {% endcomment %}
                  <td style="text-align: center;">{{ item.item.item_price }} {{ item.item.item_price_currency }}</td>
                  <td style="text-align: center;">{{ item.total_price }} {{ item.item.item_price_currency }}</td>
                </tr>
                {% endfor %}
                <tr class='card-footer text-center' style="background: #FFE4B5;">
                  <th>{% trans "Total" %}</th>
                  <td colspan="4"></td>
                  <th>{{ cart.get_total_price }} {{ item.item_price_currency }}</th>
                </tr>
              </table>
    
        </div>
        <div class='card-footer text-center' style="background: #FFE4B5;">

          <a href="{% url 'all_products_for_clients' %}" class="btn btn3">{% trans 'Continue Shopping' %}</a>
          <a href="{% url 'order_create' %}" class="btn btn3">{% trans 'Checkout' %}</a>
        </div>
    </div>
    {% else %}
    <p>{% blocktranslate %}You haven't ordered anything yet. Your cart is empty. Please add items.{% endblocktranslate %} <a class="btn btn3" href="{% url 'all_products_for_clients' %}">{% trans "All Products" %}</a></p>
    {% endif %}
</div>
{% endblock content %}

templates/category_edit.html
{% extends "_base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Edit" %}{% endblock title %}

{% block content %}
<div class="container mt-3">    
    <h1 class="h1 border-bottom pb-3 border-light border-opacity-25">{% trans "Edit" %}</h1>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn3" type="submit">{% trans "Update" %}</button>
        <a href="{% url 'category_all' %}" class="btn btn3">{% trans 'Back' %}</a>
    </form>
</div>

{% endblock content%}

templates/clients.html
{% extends "_base.html" %}
{% load i18n %}

{% block title %}{% trans "Our Clients" %}{% endblock title %}

{% block content %}
<div class="container mt-3"> 
    <h1 h1 class="h1 border-bottom pb-3 border-light border-opacity-25">{% trans "Our Clients" %}</h1>
    <p>{% blocktranslate %}The page is not created yet. {% endblocktranslate %}</p>
</div>
{% endblock content %}

templates/contactuspage.html
{% extends "_base.html" %}
{% load i18n %}

{% block title %}{% trans "Contact Us" %}{% endblock title %}

{% block content %}
<section class="contact_section layout_padding">
    <div class="mapouter"><div class="gmap_canvas"><iframe class="gmap_iframe" width="100%" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=600&amp;height=400&amp;hl=en&amp;q=Eiffel Tower&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"></iframe><a href="https://strandsgame.net/">Strands Game</a></div><style>.mapouter{position:relative;text-align:right;width:100%;height:400px;}.gmap_canvas {overflow:hidden;background:none!important;width:100%;height:400px;}.gmap_iframe {height:400px!important;}</style></div>
</section>
{% endblock content %}

templates/delivery.html
{% extends "_base.html" %}
{% load i18n %}

{% block title %}{% trans "Delivery"%}{% endblock title %}

{% block content %}
<div class="container mt-3"> 
    <h1 h1 class="h1 border-bottom pb-3 border-light border-opacity-25">{% trans "Delivery"%}</h1>
    <p>{% blocktranslate %}The page is not created yet. {% endblocktranslate %}</p>
</div>
{% endblock content %}

templates/faq.html
{% extends "_base.html" %}
{% load i18n %}

{% block title %}{% trans "FAQs" %}{% endblock title %}

{% block content %}
<div class="container mt-3"> 
    <h1 h1 class="h1 border-bottom pb-3 border-light border-opacity-25">{% trans "FAQs" %}</h1>
    <p>{% blocktranslate %}The page is not created yet. {% endblocktranslate %}</p>
</div>
{% endblock content %}

templates/home.html
{% extends "_base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "WOODNUTS" %}{% endblock title %}

{% block content %}
<!-- carousel -->
<section class="bg-dark">
    <div id="carouselExampleInterval" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active" data-bs-interval="10000">
            <img src="{% static 'images/hazelnut333.webp' %}" class="d-block w-100" alt="hazelnut">
          </div>
          <div class="carousel-item" data-bs-interval="10000">
            <img src="{% static "images/peanuts333.webp" %}" class="d-block w-100" alt="peanuts">
          </div>
          <div class="carousel-item" data-bs-interval="10000">
            <img src="{% static "images/breakfast333.webp" %}" class="d-block w-100" alt="breakfast">
          </div>
          <div class="carousel-item" data-bs-interval="10000">
            <img src="{% static 'images/mindal333.webp' %}" class="d-block w-100" alt="mindal">
          </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="visually-hidden">{% trans "Previous" %}</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="visually-hidden">{% trans "Next" %}</span>
        </button>
      </div>
</section>
<!-- Section-->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-3">
        <div class="row gx-4 gx-lg-5 row-cols-1 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for item in page_obj%}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Sale badge-->
                    {% if item.item_extra_tag %}
                    <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">{% trans item.item_extra_tag %}</div>
                    {% endif %}
                    <!-- Product image-->
                    <a href="{% url 'item_detail_for_clients' item.id %}" style="text-decoration: none; color: black;">
                        <img class="card-img-top" src="{{ item.item_picture.url }}" alt="{{ item.item_name }}" "/></a>
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h5 class="fw-bolder"><a href="{% url 'item_detail_for_clients' item.id %}" style="text-decoration: none; color: black;">{{ item.item_name }}</a></h5>
                            <!-- Product reviews-->
                            <div class="d-flex justify-content-center small text-warning mb-2">
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                                <div class="bi-star-fill"></div>
                            </div>
                            <!-- Product price-->
                            {% if item.item_price_extra_new %}
                            <span class="text-muted text-decoration-line-through">{{ item.item_price }}</span>
                            {{ item.item_price_extra_new }} {{ item.item_price_currency }}
                            {% else %}
                            {{ item.item_price }} {{ item.item_price_currency }}
                            {% endif %}
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                      <div class="container text-center" style="width: 190px;">
                        <form class="row align-items-center" action="{% url 'cart_add' item.id %}" method="post">
                          <div class="col">
                          {{ cart_product_form }}
                          {% csrf_token %}
                          </div>
                          <div class="col">
                          <input type="submit" class="btn btn-outline-dark mt-auto" value="{% trans 'Add to cart' %}">
                          </div>
                        </form>  
                      </div>
                      {% comment %} <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="#">{% trans "Add to cart" %}</a></div> {% endcomment %}
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% endblock content %}

templates/item_edit.html
{% extends "_base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Edit" %}{% endblock title %}

{% block content %}
<div class="container mt-3">    
    <h1 class="h1 border-bottom pb-3 border-light border-opacity-25">{% trans "Edit" %}</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button class="btn btn3" type="submit">{% trans "Update" %}</button>
        <a href="{% url 'item_all' %}" class="btn btn3">{% trans 'Back' %}</a>
    </form>
</div>

{% endblock content%}

templates/manager.html
{% extends "_base.html" %}
{% load i18n %}

{% block title %}{% trans "Site Management" %}{% endblock title %}

{% block content %}
<div class="container mt-3"> 
    <h1 h1 class="h1 border-bottom pb-3 border-light border-opacity-25">{% trans "Site Management" %}</h1>
    <p>{% trans 'Hello' %} {{user.first_name}} {{user.last_name}} !</p>
    <ul>
        {% if perms.products.view_category %}
        <li><a style="cursor:pointer; text-decoration:none; color:#8B4513;" href="{% url 'category_all' %}">{% trans "Category List" %}</a></li>
        {% endif %}
        {% if perms.products.add_category %}
        <li><a style="cursor:pointer; text-decoration:none; color:#8B4513;" href="{% url 'addcategory' %}">{% trans "Add Category" %}</a></li>
        {% endif %}
    </ul>
    <ul>
        {% if perms.products.view_item %}
        <li><a style="cursor:pointer; text-decoration:none; color:#8B4513;" href="{% url 'item_all' %}">{% trans "Item List" %}</a></li>
        {% endif %}
        {% if perms.products.add_item %}
        <li><a style="cursor:pointer; text-decoration:none; color:#8B4513;" href="{% url 'additem' %}">{% trans "Add Item" %}</a></li>
        {% endif %}
    </ul>
</div>
{% endblock content %}

templates/order_created.html
{% extends "_base.html" %}
{% load static %}
{% load i18n %}
{% block script %} <script src="https://js.stripe.com/v3/"></script> {% endblock script%} 

{% block title %}{% trans "Thank You!" %}{% endblock title %}

{% block content %}
<div class="container mt-3">    
    <h1 class="h1 border-bottom pb-3 border-light border-opacity-25">{% trans "Thank You!" %} </h1>
    <p>{% blocktranslate %}Your order has been successfully completed. Your order number is{% endblocktranslate %} <strong>{{ order.id }}</strong></p>
    <section>
        <p class="price">{{ order.get_total_cost }}</p>
        <form action="{% url 'create-checkout-session' order.id %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">{% trans "Pay!" %}</button>
        </form>
    </section>
</div>
{% endblock content %}

templates/order_list.html
{% extends "_base.html" %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "My Orders" %}{% endblock title %}

{% block content %}
<div class="container mt-3"> 
    <h1 h1 class="h1 border-bottom pb-3 border-light border-opacity-25">{% trans "My Orders" %}</h1>
    {% for lists in list %}
    <p><a style="cursor:pointer; text-decoration:none; color:#8B4513;" href="{% url 'orderdetail' lists.id %}">{% trans "Order number" %} {{ lists.id }}, {% trans "Total cost" %} {{ lists.get_total_cost }} RUB</a></p>
    {% endfor %}
</div>
{% endblock content %}

templates/paymentsuccess.html
{% extends "_base.html" %}
{% load i18n %}

{% block title %}{% trans "Payment Successful"%}{% endblock title %}

{% block content %}
<div class="container mt-3"> 
    <h1 h1 class="h1 border-bottom pb-3 border-light border-opacity-25">{% trans "Payment Successful"%}</h1>
    <p>{% blocktranslate %}We appreciate your business! Thanks for your order! {% endblocktranslate %}</p>
</div>
{% endblock content %}

templates/user_detail_pw_update.html
{% extends "_base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}

{% block title %}{% trans "Password Change" %}{% endblock title %}

{% block content %}
<div class="container mt-3">    
    <h1 class="h1 border-bottom pb-3 border-light border-opacity-25">{% trans "Password change" %}</h1>
    <p>{% blocktranslate %}Please enter your old password, for security's sake, and then enter your new password twice so we can verify you tiped it correctly{% endblocktranslate %}</p>

    <form action="" method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <center>
            <input type="submit" class="btn btn3" value='{% trans "Change my password" %}'>
            <a href="{% url 'home' %}" class="btn btn3">{% trans 'Home' %}</a>
        </center>
    </form>
</div>
{% endblock content %}